media:
  input: static
  output: ""
  path: static
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/blog'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: tags
        label: Tags
        list: true
        type: string
      - name: cover
        label: Cover Image
        type: object
        fields:
          - name: image
            label: Image
            type: image
      - name: body
        label: Body
        type: rich-text
  - name: projects
    label: Projects
    type: collection
    path: 'content/projects'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        type: rich-text
  - name: photography
    label: Photography
    type: collection
    path: 'content/photography'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        type: rich-text
  - name: config
    label: Hugo config
    path: hugo.yaml
    type: file
    fields:
      - name: theme
        type: string
      - name: title
        type: string
      - name: menu
        type: object
        fields:
          - name: main
            type: object
            list: true
            fields:
              - name: name
                type: string
              - name: url
                type: string
      - name: params
        type: object
        fields:
          - name: author
            type: string
          - name: showReadingTime
            type: boolean
          - name: showWordCount
            type: boolean
          - name: editPost
            type: object
            fields:
              - name: URL
                type: string
              - name: text
                type: string
              - name: appendFilePath
                type: boolean
          - name: defaultTheme
            type: string
          - name: disableThemeToggle
            type: boolean
          - name: showCodeCopyButtons
            type: boolean
          - name: profileMode
            type: object
            fields:
              - name: enabled
                type: boolean
              - name: title
                type: string
              - name: subtitle
                type: string
              - name: imageUrl
                type: image
              - name: imageWidth
                type: number
              - name: imageHeight
                type: number
          - name: socialIcons
            type: object
            list: true
            fields:
              - name: name
                type: string
              - name: url
                type: string
          - name: hideFooter
            type: boolean
      - name: disableHugoGeneratorInject
        type: boolean