media:
  input: static/media
  output: /media
  path: static/media
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/blog'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: draft
        type: boolean
        default: true
      - name: date
        type: date
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: projects
    label: Projects
    type: collection
    path: 'content/projects'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: draft
        type: boolean
        default: true
      - name: date
        type: date
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: photography
    label: Photography
    type: collection
    path: 'content/photography'
    view:
      fields: [ title, draft, date ]
    fields:
      - name: draft
        type: boolean
        default: true
      - name: date
        type: date
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: config
    label: Hugo config
    path: hugo.yaml
    type: file
    fields:
      - name: baseURL
        type: string
      - name: theme
        type: string
      - name: title
        type: string