baseURL: https://dylanbutler.dev
languageCode: en-us
theme: "PaperMod"
title: "@dbut2"
languages:
  en:
    languageAltTitle: "English"
  jp:
    languageAltTitle: "Japanese"
    profileMode:
      enabled: true
      title: "ディランバトラー"
      subtitle: "ソフトウェアエンジニア｜メルボルン"
      imageUrl: "profile.jpg"
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
    menu:
      main:
        - name: プロジェクト
          url: /projects
        - name: 写真
          url: /photography
menu:
  main:
    - name: Projects
      url: /projects
    - name: Photography
      url: /photography
params:
  defaultTheme: auto
  disableThemeToggle: false
  showCodeCopyButtons: true
  profileMode:
    enabled: true
    title: "Dylan Butler"
    subtitle: "software engineer | melbourne"
    imageUrl: "profile.jpg"
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/dbut2"
    - name: "linkedin"
      url: "https://linkedin.com/in/dbut2"
    - name: "instagram"
      url: "https://instagram.com/dbut2"
    - name: "strava"
      url: "https://strava.com/athletes/dbut2"
