baseURL: https://dylanbutler.net
languageCode: en-us
theme: "PaperMod"
title: "@dbut2"
sectionPagesMenu: "main"
params:
    defaultTheme: auto
    disableThemeToggle: false

    showReadingTime: true

    showCodeCopyButtons: true

    profileMode:
        enabled: true
        title: "Dylan Butler"
        subtitle: "software engineer | melbourne"
        imageUrl: "gopher.png"
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
    socialIcons: # optional
      - name: "github"
        url: "https://github.com/dbut2"
      - name: "linkedin"
        url: "https://linkedin.com/in/dylan-butler"
      - name: "instagram"
        url: "https://instagram.com/dbut2"
