baseURL: https://but.la
languageCode: en-us
theme: "PaperMod"
title: "@dbut2"
languages:
  en:
    weight: 1
    params:
     languageAltTitle: "English"
  mk:
    weight: 2
    params:
      languageAltTitle: "Македонски"
      profileMode:
        title: "Дилан Батлер"
        subtitle: "Софтверски инженер｜Мелбурн"
    menu:
      main:
        - name: Проекти
          url: /projects
        - name: Фотографија
          url: /photography
  jp:
    weight: 3
    params:
      languageAltTitle: "日本語"
      profileMode:
        title: "ディランバトラー"
        subtitle: "ソフトウェアエンジニア｜メルボルン"
    menu:
      main:
        - name: プロジェクト
          url: /projects
        - name: 写真
          url: /photography
menu:
  main:
    - name: Projects
      url: /projects
    - name: Photography
      url: /photography
params:
  defaultTheme: auto
  disableThemeToggle: false
  showCodeCopyButtons: true
  profileMode:
    enabled: true
    title: "Dylan Butler"
    subtitle: "software engineer | melbourne"
    imageUrl: "/profile.jpg"
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/dbut2"
    - name: "linkedin"
      url: "https://linkedin.com/in/dbut2"
    - name: "strava"
      url: "https://strava.com/athletes/dbut2"
services:
  googleAnalytics:
    id: G-JGY0G4ZPX3
