name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: gcloud Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload static
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: static
          destination: dbut-cdn/home

      - name: Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DBUT_0 }}
          channelId: live
          projectId: dbut-0
